services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interviewdb
    ports:
      - "5432:5432"
    networks:
      - interview_net
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend/.
      dockerfile: Dockerfile
    # command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - interview_net

  # frontend:
  #   build:
  #     context: ./front_end/.
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   restart: unless-stopped

networks:
  interview_net:
    driver: bridge
